### ISSUE TITLE
[Errno 54] Connection reset by peer

### ISSUE THREAD

**Issue by ocdman** [luanxinchen/switchbak#1]
我使用的是telbak.py脚本，
在启用debug日志等级5的情况下，
telnet华为交换机，
debug日志显示有返回内容，
但是在最后一个quit命令的时候，
打印Exception的内容为：[Errno 54] Connection reset by peer

**Comment by ocdman** [comment]
是不是只有华为交换机才会有这种问题

**Comment by luanxinchen** [comment]
`Connection reset by peer`一般是socket连接被客户端意外中断导致。
目前手头没有华为交换机用于测试。您可以telnet到交换机上手动执行39-46行的命令，观察执行到最后一行时交换机处于什么状态，或者在注释掉第46行quit命令后观察报错是否有变化。

**Comment by ocdman** [comment]
使用secureCRT telnet登录华为交换机后，手动执行最后一个quit命令后，secureCRT客户端提示

```
Info: The max number of VTY users is 10, and the number
      of current VTY users on line is 0.
Connection reset by peer
```

就跟使用代码捕获到的异常消息一模一样，盲猜可能是华为交换机自身的退出机制问题了，quit命令后客户端没有响应服务端的中断消息就先断掉了。

另外我尝试把46行quit命令注释掉后，客户端就不会主动断开，最后捕获异常消息提示`time out`超时

**Comment by ocdman** [comment]
目前发现一种临时的方案来解决华为交换机的备份问题，
将49行`read_all`方法替换成`read_until`方法，并使用参数`#\r\nreturn`，
这样的话，可以暂时解决因客户端连接中断导致华为交换机`read_all`失败的问题。
另外H3C也可以正常使用该方法，而且会输出最后一个quit命令的内容

**Comment by luanxinchen** [comment]
稍后我会找个华为环境测试下，感谢提供！:)
